export const cuisineList = [
  "American",
  "Weight Loss",
  "Muscle Gain",
  "High Protein",
  "Healthy",
  "Low Carb",
  "Keto",
  "Vegetarian",
  "Vegan",
  "Gluten Free",
  "Dairy Free",
  "Paleo",
  "Mediterranean",
  "Balanced",
  "Calorie Controlled",
  "Intermittent Fasting",
  "Post Workout",
  "Pre Workout",
  "Bulking",
  "Cutting",
  "Athletic Performance",
  "Recovery",
  "Clean Eating",
  "Macro Focused",
  "Plant Based",
  "Sports Nutrition",
  "Meal Prep"
];
